apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: u60eupd5x-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: u60eupd5x-go 
  name: u60eupd5x-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: u60eupd5x-go 
